export const PLANET_DATA = [
  { name: 'Mercury', textureMap: '/textures/mercury.jpg', baseRadius: 2, baseOrbitRadius: 50, color: '#a8a8a8', speed: 0.16, type: 'rock', metalness: 0.2, roughness: 0.8, info: "The smallest planet in our solar system and closest to the Sun. It has a rocky surface heavily cratered like our Moon." },
  { name: 'Venus', textureMap: '/textures/venus.jpg', baseRadius: 3, baseOrbitRadius: 70, color: '#f5c58c', speed: 0.12, type: 'gas', roughness: 0.4, info: "Often called Earth's twin due to its similar size. It has a thick, toxic atmosphere that traps heat, making it the hottest planet." },
  { name: 'Earth', textureMap: '/textures/earth.jpg', baseRadius: 5, baseOrbitRadius: 90, color: '#2b82c9', speed: 0.1, type: 'water', roughness: 0.6, metalness: 0.1, info: "Our home planet and the only known celestial body to support life. It has vast oceans of liquid water and a breathable atmosphere." },
  { name: 'Mars', textureMap: '/textures/mars.jpg', baseRadius: 4, baseOrbitRadius: 115, color: '#c1440e', speed: 0.08, type: 'rock', metalness: 0.1, roughness: 0.9, info: "Known as the Red Planet because of iron oxide (rust) on its surface. It has the largest volcano in the solar system, Olympus Mons." },
  { name: 'Jupiter', textureMap: '/textures/jupiter.jpg', baseRadius: 14, baseOrbitRadius: 170, color: '#ffaa56', speed: 0.04, type: 'gas', roughness: 0.5, info: "The largest planet in our solar system. It is a gas giant famous for its Great Red Spot, a massive storm larger than Earth." },
  { name: 'Saturn', textureMap: '/textures/saturn.jpg', baseRadius: 11, baseOrbitRadius: 230, color: '#e6b676', speed: 0.016, hasRing: true, ringColors: ['#e6b676', '#f0c384', '#fad192'], type: 'gas', roughness: 0.5, info: "Famous for its stunning, complex ring system made mostly of ice particles with a smaller amount of rocky debris and dust." },
  { name: 'Uranus', textureMap: '/textures/uranus.jpg', baseRadius: 8, baseOrbitRadius: 280, color: '#67ffaf', speed: 0.010, hasRing: true, ringColors: ['#67ffaf', '#85ffd3'], type: 'gas', roughness: 0.5, info: "An ice giant that rotates on its side, meaning its axis of rotation is nearly parallel to the plane of its orbit." },
  { name: 'Neptune', textureMap: '/textures/neptune.jpg', baseRadius: 7, baseOrbitRadius: 320, color: '#3b59ff', speed: 0.006, type: 'gas', roughness: 0.5, info: "The most distant major planet. It is incredibly windy and cold, with a vibrant blue color due to methane in its atmosphere." },
];
